'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System.Data

Namespace ServiceReferenceGestionPedidos
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="ServiceReferenceGestionPedidos.WSGestionPedidosSoap")>  _
    Public Interface WSGestionPedidosSoap
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Cliente_Agregar", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function Cliente_Agregar(ByVal ObjCliente As ServiceReferenceGestionPedidos.ClienteE) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Cliente_Agregar", ReplyAction:="*")>  _
        Function Cliente_AgregarAsync(ByVal ObjCliente As ServiceReferenceGestionPedidos.ClienteE) As System.Threading.Tasks.Task(Of Integer)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Cliente_Actualizar", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function Cliente_Actualizar(ByVal ObjCliente As ServiceReferenceGestionPedidos.ClienteE) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Cliente_Actualizar", ReplyAction:="*")>  _
        Function Cliente_ActualizarAsync(ByVal ObjCliente As ServiceReferenceGestionPedidos.ClienteE) As System.Threading.Tasks.Task(Of Integer)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Cliente_ObtenerPorCampo", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function Cliente_ObtenerPorCampo(ByVal field As String, ByVal value As String) As ServiceReferenceGestionPedidos.ClienteE
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Cliente_ObtenerPorCampo", ReplyAction:="*")>  _
        Function Cliente_ObtenerPorCampoAsync(ByVal field As String, ByVal value As String) As System.Threading.Tasks.Task(Of ServiceReferenceGestionPedidos.ClienteE)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Cliente_ObtenerTodo", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function Cliente_ObtenerTodo() As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Cliente_ObtenerTodo", ReplyAction:="*")>  _
        Function Cliente_ObtenerTodoAsync() As System.Threading.Tasks.Task(Of System.Data.DataSet)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Cliente_Borrar", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function Cliente_Borrar(ByVal ObjCliente As ServiceReferenceGestionPedidos.ClienteE) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Cliente_Borrar", ReplyAction:="*")>  _
        Function Cliente_BorrarAsync(ByVal ObjCliente As ServiceReferenceGestionPedidos.ClienteE) As System.Threading.Tasks.Task(Of Integer)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Producto_Agregar", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function Producto_Agregar(ByVal ObjProducto As ServiceReferenceGestionPedidos.ProductoE) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Producto_Agregar", ReplyAction:="*")>  _
        Function Producto_AgregarAsync(ByVal ObjProducto As ServiceReferenceGestionPedidos.ProductoE) As System.Threading.Tasks.Task(Of Integer)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Producto_Actualizar", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function Producto_Actualizar(ByVal ObjProducto As ServiceReferenceGestionPedidos.ProductoE) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Producto_Actualizar", ReplyAction:="*")>  _
        Function Producto_ActualizarAsync(ByVal ObjProducto As ServiceReferenceGestionPedidos.ProductoE) As System.Threading.Tasks.Task(Of Integer)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Producto_ObtenerPorCampo", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function Producto_ObtenerPorCampo(ByVal field As String, ByVal value As String) As ServiceReferenceGestionPedidos.ProductoE
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Producto_ObtenerPorCampo", ReplyAction:="*")>  _
        Function Producto_ObtenerPorCampoAsync(ByVal field As String, ByVal value As String) As System.Threading.Tasks.Task(Of ServiceReferenceGestionPedidos.ProductoE)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Producto_ObtenerTodo", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function Producto_ObtenerTodo() As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Producto_ObtenerTodo", ReplyAction:="*")>  _
        Function Producto_ObtenerTodoAsync() As System.Threading.Tasks.Task(Of System.Data.DataSet)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Producto_Borrar", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function Producto_Borrar(ByVal ObjProducto As ServiceReferenceGestionPedidos.ProductoE) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Producto_Borrar", ReplyAction:="*")>  _
        Function Producto_BorrarAsync(ByVal ObjProducto As ServiceReferenceGestionPedidos.ProductoE) As System.Threading.Tasks.Task(Of Integer)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/UnidadMedida_ObtenerTodo", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function UnidadMedida_ObtenerTodo() As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/UnidadMedida_ObtenerTodo", ReplyAction:="*")>  _
        Function UnidadMedida_ObtenerTodoAsync() As System.Threading.Tasks.Task(Of System.Data.DataSet)
    End Interface
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class ClienteE
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private clId1Field As Integer
        
        Private clCuit1Field As String
        
        Private clRazonSocial1Field As String
        
        Private clDireccion1Field As String
        
        Private clTelefono1Field As String
        
        Private clEmail1Field As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property ClId1() As Integer
            Get
                Return Me.clId1Field
            End Get
            Set
                Me.clId1Field = value
                Me.RaisePropertyChanged("ClId1")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=1)>  _
        Public Property ClCuit1() As String
            Get
                Return Me.clCuit1Field
            End Get
            Set
                Me.clCuit1Field = value
                Me.RaisePropertyChanged("ClCuit1")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=2)>  _
        Public Property ClRazonSocial1() As String
            Get
                Return Me.clRazonSocial1Field
            End Get
            Set
                Me.clRazonSocial1Field = value
                Me.RaisePropertyChanged("ClRazonSocial1")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=3)>  _
        Public Property ClDireccion1() As String
            Get
                Return Me.clDireccion1Field
            End Get
            Set
                Me.clDireccion1Field = value
                Me.RaisePropertyChanged("ClDireccion1")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=4)>  _
        Public Property ClTelefono1() As String
            Get
                Return Me.clTelefono1Field
            End Get
            Set
                Me.clTelefono1Field = value
                Me.RaisePropertyChanged("ClTelefono1")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=5)>  _
        Public Property ClEmail1() As String
            Get
                Return Me.clEmail1Field
            End Get
            Set
                Me.clEmail1Field = value
                Me.RaisePropertyChanged("ClEmail1")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class ProductoE
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private prId1Field As Integer
        
        Private prDescripcion1Field As String
        
        Private prUnidadMedida1Field As String
        
        Private prPrecioVenta1Field As Decimal
        
        Private prPrecioCompra1Field As Decimal
        
        Private prFechaActPrecioVenta1Field As Date
        
        Private prFechaActPrecioCompra1Field As Date
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property PrId1() As Integer
            Get
                Return Me.prId1Field
            End Get
            Set
                Me.prId1Field = value
                Me.RaisePropertyChanged("PrId1")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=1)>  _
        Public Property PrDescripcion1() As String
            Get
                Return Me.prDescripcion1Field
            End Get
            Set
                Me.prDescripcion1Field = value
                Me.RaisePropertyChanged("PrDescripcion1")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=2)>  _
        Public Property PrUnidadMedida1() As String
            Get
                Return Me.prUnidadMedida1Field
            End Get
            Set
                Me.prUnidadMedida1Field = value
                Me.RaisePropertyChanged("PrUnidadMedida1")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=3)>  _
        Public Property PrPrecioVenta1() As Decimal
            Get
                Return Me.prPrecioVenta1Field
            End Get
            Set
                Me.prPrecioVenta1Field = value
                Me.RaisePropertyChanged("PrPrecioVenta1")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=4)>  _
        Public Property PrPrecioCompra1() As Decimal
            Get
                Return Me.prPrecioCompra1Field
            End Get
            Set
                Me.prPrecioCompra1Field = value
                Me.RaisePropertyChanged("PrPrecioCompra1")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=5)>  _
        Public Property PrFechaActPrecioVenta1() As Date
            Get
                Return Me.prFechaActPrecioVenta1Field
            End Get
            Set
                Me.prFechaActPrecioVenta1Field = value
                Me.RaisePropertyChanged("PrFechaActPrecioVenta1")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=6)>  _
        Public Property PrFechaActPrecioCompra1() As Date
            Get
                Return Me.prFechaActPrecioCompra1Field
            End Get
            Set
                Me.prFechaActPrecioCompra1Field = value
                Me.RaisePropertyChanged("PrFechaActPrecioCompra1")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface WSGestionPedidosSoapChannel
        Inherits ServiceReferenceGestionPedidos.WSGestionPedidosSoap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class WSGestionPedidosSoapClient
        Inherits System.ServiceModel.ClientBase(Of ServiceReferenceGestionPedidos.WSGestionPedidosSoap)
        Implements ServiceReferenceGestionPedidos.WSGestionPedidosSoap
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function Cliente_Agregar(ByVal ObjCliente As ServiceReferenceGestionPedidos.ClienteE) As Integer Implements ServiceReferenceGestionPedidos.WSGestionPedidosSoap.Cliente_Agregar
            Return MyBase.Channel.Cliente_Agregar(ObjCliente)
        End Function
        
        Public Function Cliente_AgregarAsync(ByVal ObjCliente As ServiceReferenceGestionPedidos.ClienteE) As System.Threading.Tasks.Task(Of Integer) Implements ServiceReferenceGestionPedidos.WSGestionPedidosSoap.Cliente_AgregarAsync
            Return MyBase.Channel.Cliente_AgregarAsync(ObjCliente)
        End Function
        
        Public Function Cliente_Actualizar(ByVal ObjCliente As ServiceReferenceGestionPedidos.ClienteE) As Integer Implements ServiceReferenceGestionPedidos.WSGestionPedidosSoap.Cliente_Actualizar
            Return MyBase.Channel.Cliente_Actualizar(ObjCliente)
        End Function
        
        Public Function Cliente_ActualizarAsync(ByVal ObjCliente As ServiceReferenceGestionPedidos.ClienteE) As System.Threading.Tasks.Task(Of Integer) Implements ServiceReferenceGestionPedidos.WSGestionPedidosSoap.Cliente_ActualizarAsync
            Return MyBase.Channel.Cliente_ActualizarAsync(ObjCliente)
        End Function
        
        Public Function Cliente_ObtenerPorCampo(ByVal field As String, ByVal value As String) As ServiceReferenceGestionPedidos.ClienteE Implements ServiceReferenceGestionPedidos.WSGestionPedidosSoap.Cliente_ObtenerPorCampo
            Return MyBase.Channel.Cliente_ObtenerPorCampo(field, value)
        End Function
        
        Public Function Cliente_ObtenerPorCampoAsync(ByVal field As String, ByVal value As String) As System.Threading.Tasks.Task(Of ServiceReferenceGestionPedidos.ClienteE) Implements ServiceReferenceGestionPedidos.WSGestionPedidosSoap.Cliente_ObtenerPorCampoAsync
            Return MyBase.Channel.Cliente_ObtenerPorCampoAsync(field, value)
        End Function
        
        Public Function Cliente_ObtenerTodo() As System.Data.DataSet Implements ServiceReferenceGestionPedidos.WSGestionPedidosSoap.Cliente_ObtenerTodo
            Return MyBase.Channel.Cliente_ObtenerTodo
        End Function
        
        Public Function Cliente_ObtenerTodoAsync() As System.Threading.Tasks.Task(Of System.Data.DataSet) Implements ServiceReferenceGestionPedidos.WSGestionPedidosSoap.Cliente_ObtenerTodoAsync
            Return MyBase.Channel.Cliente_ObtenerTodoAsync
        End Function
        
        Public Function Cliente_Borrar(ByVal ObjCliente As ServiceReferenceGestionPedidos.ClienteE) As Integer Implements ServiceReferenceGestionPedidos.WSGestionPedidosSoap.Cliente_Borrar
            Return MyBase.Channel.Cliente_Borrar(ObjCliente)
        End Function
        
        Public Function Cliente_BorrarAsync(ByVal ObjCliente As ServiceReferenceGestionPedidos.ClienteE) As System.Threading.Tasks.Task(Of Integer) Implements ServiceReferenceGestionPedidos.WSGestionPedidosSoap.Cliente_BorrarAsync
            Return MyBase.Channel.Cliente_BorrarAsync(ObjCliente)
        End Function
        
        Public Function Producto_Agregar(ByVal ObjProducto As ServiceReferenceGestionPedidos.ProductoE) As Integer Implements ServiceReferenceGestionPedidos.WSGestionPedidosSoap.Producto_Agregar
            Return MyBase.Channel.Producto_Agregar(ObjProducto)
        End Function
        
        Public Function Producto_AgregarAsync(ByVal ObjProducto As ServiceReferenceGestionPedidos.ProductoE) As System.Threading.Tasks.Task(Of Integer) Implements ServiceReferenceGestionPedidos.WSGestionPedidosSoap.Producto_AgregarAsync
            Return MyBase.Channel.Producto_AgregarAsync(ObjProducto)
        End Function
        
        Public Function Producto_Actualizar(ByVal ObjProducto As ServiceReferenceGestionPedidos.ProductoE) As Integer Implements ServiceReferenceGestionPedidos.WSGestionPedidosSoap.Producto_Actualizar
            Return MyBase.Channel.Producto_Actualizar(ObjProducto)
        End Function
        
        Public Function Producto_ActualizarAsync(ByVal ObjProducto As ServiceReferenceGestionPedidos.ProductoE) As System.Threading.Tasks.Task(Of Integer) Implements ServiceReferenceGestionPedidos.WSGestionPedidosSoap.Producto_ActualizarAsync
            Return MyBase.Channel.Producto_ActualizarAsync(ObjProducto)
        End Function
        
        Public Function Producto_ObtenerPorCampo(ByVal field As String, ByVal value As String) As ServiceReferenceGestionPedidos.ProductoE Implements ServiceReferenceGestionPedidos.WSGestionPedidosSoap.Producto_ObtenerPorCampo
            Return MyBase.Channel.Producto_ObtenerPorCampo(field, value)
        End Function
        
        Public Function Producto_ObtenerPorCampoAsync(ByVal field As String, ByVal value As String) As System.Threading.Tasks.Task(Of ServiceReferenceGestionPedidos.ProductoE) Implements ServiceReferenceGestionPedidos.WSGestionPedidosSoap.Producto_ObtenerPorCampoAsync
            Return MyBase.Channel.Producto_ObtenerPorCampoAsync(field, value)
        End Function
        
        Public Function Producto_ObtenerTodo() As System.Data.DataSet Implements ServiceReferenceGestionPedidos.WSGestionPedidosSoap.Producto_ObtenerTodo
            Return MyBase.Channel.Producto_ObtenerTodo
        End Function
        
        Public Function Producto_ObtenerTodoAsync() As System.Threading.Tasks.Task(Of System.Data.DataSet) Implements ServiceReferenceGestionPedidos.WSGestionPedidosSoap.Producto_ObtenerTodoAsync
            Return MyBase.Channel.Producto_ObtenerTodoAsync
        End Function
        
        Public Function Producto_Borrar(ByVal ObjProducto As ServiceReferenceGestionPedidos.ProductoE) As Integer Implements ServiceReferenceGestionPedidos.WSGestionPedidosSoap.Producto_Borrar
            Return MyBase.Channel.Producto_Borrar(ObjProducto)
        End Function
        
        Public Function Producto_BorrarAsync(ByVal ObjProducto As ServiceReferenceGestionPedidos.ProductoE) As System.Threading.Tasks.Task(Of Integer) Implements ServiceReferenceGestionPedidos.WSGestionPedidosSoap.Producto_BorrarAsync
            Return MyBase.Channel.Producto_BorrarAsync(ObjProducto)
        End Function
        
        Public Function UnidadMedida_ObtenerTodo() As System.Data.DataSet Implements ServiceReferenceGestionPedidos.WSGestionPedidosSoap.UnidadMedida_ObtenerTodo
            Return MyBase.Channel.UnidadMedida_ObtenerTodo
        End Function
        
        Public Function UnidadMedida_ObtenerTodoAsync() As System.Threading.Tasks.Task(Of System.Data.DataSet) Implements ServiceReferenceGestionPedidos.WSGestionPedidosSoap.UnidadMedida_ObtenerTodoAsync
            Return MyBase.Channel.UnidadMedida_ObtenerTodoAsync
        End Function
    End Class
End Namespace
